### ISSUE TITLE
TRACKING ISSUE: Users module

### ISSUE THREAD

**Issue by PythonCreator27** [PythonCreator27/use-github-api-rs#2]
This is a tracking issue for the [users module](https://docs.github.com/en/rest/reference/users).

## TODO
- [ ] Contextual information for a user
- [ ] Get current user
- [ ] Update the current user
- [ ] Emails
- [ ] Blocks
- [ ] GPG Keys
- [ ] SSH Keys
- [ ] Followers
